// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH7z26Oxb0NeFVcmYbnxkH6ROO8qPL7U8',
    appId: '1:694382042623:web:5e7c00566bce75c682dbca',
    messagingSenderId: '694382042623',
    projectId: 'restaurantapp-e7b05',
    authDomain: 'restaurantapp-e7b05.firebaseapp.com',
    storageBucket: 'restaurantapp-e7b05.appspot.com',
    measurementId: 'G-0QVQBPBFBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMuNGHReEBQq_YxHx8euKIj-P43CpYYXw',
    appId: '1:694382042623:android:b29e94c252bb6e8582dbca',
    messagingSenderId: '694382042623',
    projectId: 'restaurantapp-e7b05',
    storageBucket: 'restaurantapp-e7b05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy-M8KFsfXMEEBhRv5Y3Z1fzvTjJ6kNC8',
    appId: '1:694382042623:ios:caf89df29be16c1282dbca',
    messagingSenderId: '694382042623',
    projectId: 'restaurantapp-e7b05',
    storageBucket: 'restaurantapp-e7b05.appspot.com',
    iosBundleId: 'com.example.restaurantapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy-M8KFsfXMEEBhRv5Y3Z1fzvTjJ6kNC8',
    appId: '1:694382042623:ios:a5fb1a9d2b70337782dbca',
    messagingSenderId: '694382042623',
    projectId: 'restaurantapp-e7b05',
    storageBucket: 'restaurantapp-e7b05.appspot.com',
    iosBundleId: 'com.example.restaurantapp.RunnerTests',
  );
}
